# Generated by Django 2.2.3 on 2019-07-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190725_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, editable=False, verbose_name='正文html代码'),
        ),
    ]
